### ISSUE TITLE
Feature Request: add ability to pull Todoist link

### ISSUE THREAD

**Issue by bcohen44** [hkgnp/logseq-todoist-plugin#11]
Just thought of a cool feature request.  When we don't want to clear the tasks from Todoist, have an option to on pull to copy the Todoist link to the task into Logseq `TODO [task title](Todoist task link)`.     That way if we want to manually keep track in Logseq, we can quickly go to the task in Todoist and check it off

**Comment by hkgnp** [comment]
Hi! I was taking a look at this feature and realise that when I try to go to a Todoist task link, it just brings me back to Todoist. 

Can I check with you if this is the case?

**Comment by bcohen44** [comment]
Ahh, yes, I see this too.  THis is a Todoist bug.  Those "Copy Link" from the UI are supposed to open specifically to the TOdoist task.  They have in the past.

**Comment by hkgnp** [comment]
> Ahh, yes, I see this too.  THis is a Todoist bug.  Those "Copy Link" from the UI are supposed to open specifically to the TOdoist task.  They have in the past.

Yeah it means that I won't be able to implement your feature request. So sorry about that!

**Comment by bcohen44** [comment]
@hkgnp This looks to be fixed, I am running Todoist Beta

**Comment by hkgnp** [comment]
Oh! Hmm how do you get Todoist Beta?

I guess the other question is how to differentiate such users so that their experience isn't affected.

**Comment by hkgnp** [comment]
Closing this issue until Todoist re-implements task link.
