### ISSUE TITLE
Feature Request: Send task to Todoist with due date

### ISSUE THREAD

**Issue by keelancook** [hkgnp/logseq-todoist-plugin#13]
Love the potential of this plugin! Thanks for the work on it.

If you can already do this, I'm missing it. I have it set where I can both pull tasks from Todoist and send tasks to Todoist. I believe I will use both. However, I would really love to be able to send the task to Todoist with either (1) a scheduled parameter from Logseq that turns into the due date for the task in Todoist or (2) merely setting a default due date in the settings on Logseq for all tasks sent to Todoist.

You already have the option to send tasks with a specific label. I'd love to be be able to send them all marked as due today (for instance) so that come in to Todoist with a due date applied. This would allow my current sorting practice to batch them with the other tasks for the the day. 

Let me know if I'm not making sense. Again, I like what you're doing here!

**Comment by hkgnp** [comment]
Thanks for your suggestion! I haven't worked on this plugin for some time so I need to take a look! It is definitely possible but do give me some time.

Thanks!

**Comment by keelancook** [comment]
No worries! I'm just glad you made this in the first place. It's a real
help already.

Being able to pull in other properties (especially due date), or send them,
would just be icing on the top.

Thanks for your work!

**Comment by hkgnp** [comment]
Hi! I implemented the send due date (but only either yes or no) in v3.2 in the marketplace.

**Comment by keelancook** [comment]
Excellent! I'll give it a spin. Thanks so much.
