### ISSUE TITLE
Unable to find app on Marketplace

### ISSUE THREAD

**Issue by tdv-nz** [hkgnp/logseq-todoist-plugin#14]
Plugin is no longer able to be found on Marketplace

**Comment by hkgnp** [comment]
Hmm, I still see it in the marketplace though. 

<img width="394" alt="Screenshot 2022-01-13 at 9 19 37 AM" src="https://user-images.githubusercontent.com/47936793/149248719-219ac234-441e-4f2c-9448-395b4c3095e5.png">

**Comment by tdv-nz** [comment]
Odd, after restarting the Logseq app out about 3 times it has appeared - now im having trouble getting my settings to stick!

**Comment by hkgnp** [comment]
Oh so sorry to hear that. Did you click Save and Close? You can then go into the settings.json file after that to see if it really got saved.

**Comment by hkgnp** [comment]
If you are still experiencing this, please try v3.2 in the marketplace.
