### ISSUE TITLE
Not getting option to enter variables

### ISSUE THREAD

**Issue by richd67** [hkgnp/logseq-todoist-plugin#15]
When I click on settings it simply opens the settings file and does not give me the option to enter the API as described in the read me

**Comment by Jdwoodson** [comment]
I am also seeing this behaviour

**Comment by Jdwoodson** [comment]
![image](https://user-images.githubusercontent.com/23250434/149743291-d0a6d652-ed5c-4d42-803f-539743a3ba1c.png)

@richd67 I was having the same issue until I realized I needed to click THIS button in the upper right corner of Logseq after installing from the marketplace and restarting.

**Comment by richd67** [comment]
Thanks, obvious when you know

**Comment by hkgnp** [comment]
Apologies guys! I'm not sure why GitHub doesn't regularly email me about posted issues. 

Yes the button there is the one that contains the settings that you can choose, etc. 

Do let me know if there's anything else. Will check back on this page again!
