### ISSUE TITLE
My tasks are deleted in Todoist when pulling into Logseq 😱

### ISSUE THREAD

**Issue by gila2000** [hkgnp/logseq-todoist-plugin#16]
Hi. I'm using the todoits-logseq plugin for the first time and in my first tests I have lost (and then recovered, several times, with a high dedicated time) all my tasks of the day.
Every time I load in Logseq with the pull command the tasks are deleted from Todoist, even if I unchecked or checked the box corresponding to the Todoist deletion.
Please can you send me a picture of how the plugin should be configured so that I can load Todoist tasks into Logseq (and vice versa) and not have them deleted in either app?
Thank you very much for your work, it is super useful for me.

**Comment by hkgnp** [comment]
Oh dear, can you try again in v3.2?

**Comment by hkgnp** [comment]
You can click update from your plugins page!

Yes, just leave it unchecked. And make sure you click Save and Close
instead of just closing.
