### ISSUE TITLE
Remove "TODO" when sending a task to Todoist etc

### ISSUE THREAD

**Issue by P1Rebo** [hkgnp/logseq-todoist-plugin#18]
First of all, thanks for this cool plugin!
Is there any possibility to configure (or avoid by default) the "TODO" or "DONE" etc text when sending a task to Todoist?
Is it also plan to pass also a description via attribute in LogSeq?

Thanks

**Comment by hkgnp** [comment]
Yup, just use the Project ID with Prefix option and leave the Project ID
without Prefix option blank.

As for the description as an attribute, I think it's already in place, but
I will need to check!

**Comment by aadilayub** [comment]
Do we have to configure this in the JSON settings? I couldn't figure out how to do this in the GUI

![todoist-logseq](https://user-images.githubusercontent.com/31581044/153535335-53d9722f-4af6-48b3-9dcb-508a7b5f0d6d.png)

**Comment by hkgnp** [comment]
Choose the second option and leave the first option blank! This will have tasks brought over and not append a prefix to it.

<img width="376" alt="Screenshot 2022-02-11 at 11 59 18 AM" src="https://user-images.githubusercontent.com/47936793/153535583-800a6257-ec0f-4aa5-9894-9dbe0040e4e8.png">

**Comment by aadilayub** [comment]
Apologies, I'm a little confused. Aren't those the options for pulling tasks, not sending them to Todoist? What I want to do is send tasks to Todoist without having TODO/DOING/DONE/NOW/LATER appended to them

**Comment by hkgnp** [comment]
Oh! I must have misunderstood.
Hmmm then perhaps you can remove them in Logseq before sending it over?
It’s currently not possible to have it automatically done.

**Comment by P1Rebo** [comment]
Thanks for the fast replies. Yes, it's LogSeq > Todoist what I meant. Currently my workflow is to send a task and afterwards include "TODO" or "DOING".
It would be good having an option to remove prefixes :-)

**Comment by hkgnp** [comment]
Hi, do you mean you will include TODO and DOING in Todoist after you send
it over?

**Comment by P1Rebo** [comment]
Remove I mean.

Example:
Logseq
[ ] TODO MyTask ==> /send to todoist

Todoist Inbox:
[ ] MyTask

**Comment by hkgnp** [comment]
Feature now available in v3.3.0 in the marketplace. Please update and try.

**Comment by P1Rebo** [comment]
Nice, works like a charm! Thanks @hkgnp !
