### ISSUE TITLE
Beyond todoist ?

### ISSUE THREAD

**Issue by bepolymathe** [hkgnp/logseq-todoist-plugin#19]
Hi @hkgnp 

First of all, thank you for your wonderful work on the plugins. I'm writing here because I know that there are some users (including me 😃) who are not developers but would be very interested in using the "sendToTodoist" feature for other software. I'm thinking for example of the very good GTD Everdo application which offers an API and a local storage of data. 

https://everdo.net/

https://help.everdo.net/docs/advanced/api/

I have the impression that your agility to code would take you little time to offer a new plugin to the community 😃 of the same order for todoist 🤔. I'm unfortunately not able to do that myself 🥺. Besides I think it would be interesting to have a "SendToTerminal" type plugin to send blocks to other application via terminal. 
Obviously I would totally understand that you wouldn't be interested at all if you don't use the tool... but your plugins create envy 😃.
That's it for my evening thought 😃

**Comment by hkgnp** [comment]
Hi!

Apologies, I don't use Everdo so I don't think I'll be making a plugin for it. Feel free to put up a request at https://discuss.logseq.com/c/feature-requests and maybe some other plugin developers who use it will be interested to make one for it!
