### ISSUE TITLE
Feature Request: Select target project (or task) before sending

### ISSUE THREAD

**Issue by P1Rebo** [hkgnp/logseq-todoist-plugin#20]
Hi @hkgnp,

it would be very nice to have the possibility while sending a "TODO" from Logseq to Todois to select the target Todoist project.
Currently every task will be created in the Inbox or another default project.

Even cooler would be the possibility to add a Logseq "TODO" to a Todoist task, in order to create a subtask.

Is there any chance to extend the plugin like this?

Thanks a lot!

**Comment by P1Rebo** [comment]
@hkgnp Is there any update on this idea? Thanks!

**Comment by hkgnp** [comment]
I am currently working on a refactor. The first request will be available.
For the second request, I am not sure what you mean. Are you referring to creating subtasks from Logseq?

**Comment by hkgnp** [comment]
Breaking change: Did a major refactor. Now when you send tasks, there is a popup to indicate the above parameters. Do update if you require the change.

**Comment by qqwxp** [comment]
> I am currently working on a refactor. The first request will be available.
> For the second request, I am not sure what you mean. Are you referring to creating subtasks from Logseq?

I think it would more useful.

**Comment by hkgnp** [comment]
> > I am currently working on a refactor. The first request will be available.
> > For the second request, I am not sure what you mean. Are you referring to creating subtasks from Logseq?
> 
> I think it would more useful.

I will be closing this FR as technically it has been completed. For creating of subtasks, perhaps if it's really needed, a new FR can be created. I am not so keen on it as I don't really use it, but will be happy to hear what the rest thinks.
