### ISSUE TITLE
Add scheduled time 

### ISSUE THREAD

**Issue by Rumpoled** [hkgnp/logseq-todoist-plugin#21]
This plugin is great!

Would it be possible to enhance the plug in so that it pulls/sends the time that an item is scheduled for? At the moment if you have a todo in todoist scheduled for '6pm today', the plugin will pull the date, but not the time it is scheduled for.

**Comment by hkgnp** [comment]
This should be available in v3.3.1 but only for pulling tasks and not for sending tasks.

**Comment by Rumpoled** [comment]
That's great! Thank you :)

**Comment by hkgnp** [comment]
Breaking change: Did a major refactor. Now when you send tasks, there is a popup to indicate the above parameters. Do update if you require the change.
