### ISSUE TITLE
Today's Tasks

### ISSUE THREAD

**Issue by WillPlatnick** [hkgnp/logseq-todoist-plugin#22]
Would it be possible to get rid of the opinionated "Tasks for Today" and nesting tasks when pulling in today's tasks?

If we change the behavior to just put tasks where the cursor is when the command is run, it could more fully support our own custom templates and also gets rid of the issue where if we pull multiple times per day, we'll have multiple Tasks for Today blocks.

**Comment by hkgnp** [comment]
Should be fixed in v4.0.0
