### ISSUE TITLE
Today's tasks method needs a timezone filter

### ISSUE THREAD

**Issue by dharshatharan** [hkgnp/logseq-todoist-plugin#23]
When I pull my today's tasks from Todoist, it seems to pull tomorrow's tasks. I think this is because it is currently 9 pm ET in Ontario, Canada (where I live), which is the next day in UTC. So I'm guessing we should be specifying the timezone as well or something equivalent.

**Comment by array** [comment]
I live in Japan,so JTC is UTC+9.
Please think timezone,or use Logseq's Day.

**Comment by hkgnp** [comment]
Should be fixed in v4.0.0
