### ISSUE TITLE
Crashes logseq when clicking the button

### ISSUE THREAD

**Issue by jarodise** [hkgnp/logseq-todoist-plugin#25]
Logseq verion 0.6.9 on Macbook Pro(x64)
Todoist Plugin version v4.1.3

Error Message: Error to get project IDs. 

the top tag is now [[undefined]] instead of [[inbox]] 

Whole logseq program will freeze when clicking on the todoist plugin button on the top bar, have to force quit and restart to continue using logseq.

**Comment by hkgnp** [comment]
As corresponded on Twitter, this issue is resolved.
