### ISSUE TITLE
The pull today tasks command only retrieve tasks in specific project

### ISSUE THREAD

**Issue by BuiKiem** [hkgnp/logseq-todoist-plugin#27]
Thank you for your hard work on such a wonderful project

I'm having weird behavior with the `pull today's tasks` commands described below

- Versions:
  - `logseq`: 0.6.9
  - `logseq-todoist-plugin`: 4.1.8

1. The `pull today's tasks` command only retrieves tasks in a specific project. As I debug in the dev tool, I think the root cause is that like the request to the Todoist API includes the `project_id` parameter, not sure if it's intentional
2. When testing the command with the project having due today tasks, the plugin does not render the tasks to the UI even though the API does return the tasks (image below)
![image](https://user-images.githubusercontent.com/28059306/169545884-d67a587d-a6c7-4168-a41d-fdc66516013d.png)

**Comment by hkgnp** [comment]
Sounds like a bug.
Could you try with v4.1.9?

**Comment by BuiKiem** [comment]
The `pull today's tasks` works as expected. You rock!!!
