### ISSUE TITLE
Featured Request: Add todoist subproyect Name as Parent Block

### ISSUE THREAD

**Issue by edu-zam** [hkgnp/logseq-todoist-plugin#28]
Hello: 
It would be really useful to have the choise to select the Todoist's subproyect name as Parent block in Logseq.
It helps  to put in the right order every action of every subproyect defined in Todoist before.

Thanks!

**Comment by hkgnp** [comment]
Sorry I’m not really sure Quay you mean? Do you have examples?

**Comment by edu-zam** [comment]
Hello, thanks for answer. 

Yes, for example I have 2 to-dos in differentes subproyects: 
![image](https://user-images.githubusercontent.com/74326159/169641979-1662bbbd-ed2f-4da7-970a-d4a09ba1c7a6.png)


They appear in this way in Logseq:
![image](https://user-images.githubusercontent.com/74326159/169641955-ce9e7a3b-6ba2-4870-8408-81dc0a6ca7df.png)


It will be great if the subproyect name could be appear like a Parent block in logseq:
![image](https://user-images.githubusercontent.com/74326159/169641999-6da84b01-1ba7-469f-80a0-4cd2e04769d6.png)

(or without the "LA/" string

Hope it's clear :P

**Comment by hkgnp** [comment]
Please see v4.2.0.

**Comment by edu-zam** [comment]
Oh this is amaaaazing! 4.2.0 it's really great! Thanks!


But it will be better if I could name the Parent block with the **subproyect** name:

![image](https://user-images.githubusercontent.com/74326159/169796578-76388ac3-7170-4f33-9b7f-3df24358af23.png)


![image](https://user-images.githubusercontent.com/74326159/169797194-547310fa-eae0-4c6b-afe0-428d11471b79.png)




Thanks!

**Comment by hkgnp** [comment]
Hmmm, how do you create sub projects in Todoist?

**Comment by edu-zam** [comment]
It's a section: 
![image](https://user-images.githubusercontent.com/74326159/170032571-c08a371a-e3a6-4cf6-8bff-15f6431b471a.png)
