### ISSUE TITLE
Not able to pull in tasks from default Inbox

### ISSUE THREAD

**Issue by jarodise** [hkgnp/logseq-todoist-plugin#30]
After updating to 0.7.2 today, I find that I am no longer able to pull in tasks that are created under the default inbox, I can pull in tasks that are under today or any other self defined projects, but not the default inbox, I've tried to reinstall the plugin, re-generate the access token, doesn't work. 

Any idea how I can solve this problem?

**Comment by aleemshaunali** [comment]
On 0.7.3 and I can't pull any tasks either 'Today' or from Project/s. Can push tasks but not pull.

**Comment by hkgnp** [comment]
Sorry for the delayed response. I am still able to pull tasks in 0.7.3. Are there any errors in the console?

**Comment by jarodise** [comment]
in 0.7.3, everything works again, I guess the malfunction was caused by some glitch in 0.7.2
