### ISSUE TITLE
With version v4.3.0 is not possible to pull tasks with comments from TODOIST to LOGSEQ?

### ISSUE THREAD

**Issue by esolag** [hkgnp/logseq-todoist-plugin#35]
Hi hkgnp.

First of all thank you and congratulations for your logseq-todoist-plugin.

I use it in may daily GTD workflow as tool for the capture stage, pulling from TODOIST to LOGSEQ all my stuff, and till some days ago it works perfectly.

The problem is that, I do not know if due to the last LOGSEQ updates or your pluging updates, but now the pulling functions are not working. 

Do you know if someone has had the same problem and how do you suggest to restart the plugin?.

Many thanks in advance and best regards.

**Comment by esolag** [comment]
After many tests and changes it seems that something is wrong with my todoist account.
 
I've changed to a new TODOIST user and now everything is working properly. :-)

**Comment by hkgnp** [comment]
Should be fixed in v5.1.1. Please re-open the issue if the problem persists.
