### ISSUE TITLE
Send Task => Web / App Links

### ISSUE THREAD

**Issue by P1Rebo** [hkgnp/logseq-todoist-plugin#37]
Hi @hkgnp,

it would be cool if there would be a preference regarding the link type that's created within Logseq after sending a task to todoist.
With current code the link to todoist goes always to the website, e.g. https://todoist.com ...
If the app is installed on the pc the deep link would be more useful, e.g. todoist://task?id= ...

For me it would be fine if there would be a default option either App or Web Link since I always prefer the app link as default.

Thanks in advance!

**Comment by P1Rebo** [comment]
Hi @hkgnp 
Any updates?

**Comment by yoghurtdewdew** [comment]
I see an option to Append Logseq URI. I opened this option but see no URI link in Todoist after sending tasks. Is that normal?

**Comment by hkgnp** [comment]
Available in latest release.
