### ISSUE TITLE
Unable to Pull Tasks without appending TODO 

### ISSUE THREAD

**Issue by gammonmark** [hkgnp/logseq-todoist-plugin#39]
Recently setup the plugin and all is working fine other than the setting for "Pulling Tasks - Append TODO by Default". When togged off, the pull still appends TODO to the tasks when they are pulled into Logseq. Looking at the .json file confirms that is set to "false" but seems to make no difference if the toggle is on or off, the TODO is always default appended. Tried toggling the plugin itself with no luck. 

Mac OS: 12.4
Logseq: 0.7.6
Todoist Plugin: 4.3.0

**Comment by hkgnp** [comment]
Should be fixed in v5.1.1. Please re-open the issue if the problem persists.
