### ISSUE TITLE
Pulling todays tasks does not pull "subtasks"

### ISSUE THREAD

**Issue by gpillemermbww** [hkgnp/logseq-todoist-plugin#40]
This issue has different behaviour depending on whether "addParentBlock" is selected or not:

If "addParentBlock" is selected no subtasks are pulled at all.

Steps to reproduce:
1) In Todoist, create a subtask of an existing task and schedule it for today
2) Try pull in "today's" tasks. It won't appear.

If "addParentBlock" is not selected subtasks are only pulled if both it and parent task are scheduled for today.
Steps to reproduce:
1) In Todoist, create a subtask of an existing task and schedule BOTH for today
2) Try pull in "today's" tasks. Subtasks will appear.
3) Remove Today from parent task - now pull tasks again, and subtask will NOT appear.

**Comment by hkgnp** [comment]
Should be fixed in v5.1.1. Please re-open the issue if the problem persists.
