### ISSUE TITLE
Pulling Wrong Scheduled Date (Sometimes)

### ISSUE THREAD

**Issue by 23727** [hkgnp/logseq-todoist-plugin#42]
Good evening, 

I'm finding that for some of my tasks pulled from Todoist, the scheduled date is one day earlier than the date I have in Todoist.

This does not appear to be the case for all the tasks. 

I wanted to post this bug for awareness and to see if others have experienced this as well. 

Thank you.

**Comment by hkgnp** [comment]
Should be fixed in v5.1.1. Please re-open the issue if the problem persists.
