### ISSUE TITLE
Settings Schema Error

### ISSUE THREAD

**Issue by daviddelven** [hkgnp/logseq-todoist-plugin#44]
Hello. 

When I go to settings, a red banner appears with "Settings Schema Error"

**Comment by daviddelven** [comment]
![image](https://user-images.githubusercontent.com/30874683/190084572-86c566f4-2b63-477b-aa3c-49f2af7e2389.png)

**Comment by mruderman** [comment]
@daviddelven  Where you ever able to resolve this?

**Comment by hkgnp** [comment]
Please try v5.0.3.

**Comment by hkgnp** [comment]
Should be fixed in v5.1.1. Please re-open the issue if the problem persists.
