### ISSUE TITLE
Tasks Disappear

### ISSUE THREAD

**Issue by mujihuz** [hkgnp/logseq-todoist-plugin#45]
I just installed the plugin but out of 10 tasks that I send to Todoist, 8 to 9 of them disappear. (The block in Logseq becomes empty, and the task in todoist gets imported as empty as well). 
any idea why this happens and how it can be fixed?

**Comment by hkgnp** [comment]
Hmm, I am not able to replicate this issue. Do you have other plugins installed?

**Comment by mujihuz** [comment]
Yes I have many others installed. 
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/86186715/194739887-a02307e9-5a90-4ea5-8787-c4036a425888.png">
![image](https://user-images.githubusercontent.com/86186715/194739888-c72f1553-d7b3-408a-a52c-1943b402d712.png)

**Comment by OleMussmann** [comment]
Tasks disappear for me as well. Pulling tasks into logseq gets the whole task list, _except the first task_. But the whole list is dropped from Todoist.

Other plugins installed, but disabled:
- Automatic Linker
- logseq-calendar-plugin
- Journals calendar
- TODO Exploder

**Comment by hkgnp** [comment]
Please try v5.0.3.

**Comment by hkgnp** [comment]
Should be fixed in v5.1.1. Please re-open the issue if the problem persists.
