### ISSUE TITLE
How to add the command in a template and make it auto-run

### ISSUE THREAD

**Issue by ferranrego** [hkgnp/logseq-todoist-plugin#47]
Hi,

firstly, thanks @hkgnp for developing for this plugin, it really made my life easier.

I'm opening this issue because:

1. I have a template that is executed daily and it appears on my journal block.
2. I would like the command `/pull today` to be executed and generate the list of task of that day automatically.

Is that possible? Adding the command to the template now executes the command instead of waiting to execute it every midnight.

Thanks!

**Comment by hkgnp** [comment]
Hi!
It is technically possible, but it is not something that everyone may need
it. Will need to regularly background-check the system to see if it's
midnight (when the computer is on) and then execute the script.

**Comment by ferranrego** [comment]
Thanks for the answer, this is how I do it with the "Unfinished business" plugin:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/3515290/196901964-1f15c45e-5b08-4d60-97bd-e0d26b7570f2.png">

Is there something similar with todoist plugin?

**Comment by hkgnp** [comment]
I see what you mean. Apologies. I don't use templates in my workflows
actually.
It is possible to use macrorenderer for this, but will need to add it in as
a new feature. However, it has been a crazy year and I am not able to
commit to when I can implement it though!
Will work on this when I have time.

**Comment by hkgnp** [comment]
Please update the plugin and setup your template as follows:

<img width="304" alt="Screenshot 2022-11-05 at 5 52 15 PM" src="https://user-images.githubusercontent.com/47936793/200113946-7505e410-457f-44ba-9e21-048a8227bd6d.png">

Let me know if it works.

**Comment by ferranrego** [comment]
Hi @hkgnp, thanks for this update. I'm not sure if I do it well, but the string {{renderer: todoist_randomword}} still stays in the page after being executed, and then every time I interact with the tasks or the block, it executes again.

**Comment by hkgnp** [comment]
Apologies could you try to update to the latest version and try to set it up again?

**Comment by ferranrego** [comment]
Works like a charm now, many thanks @hkgnp!!

**Comment by p1ntobean** [comment]
Has this item been deprecated in later releases?
