### ISSUE TITLE
Todoist all tasks not working

### ISSUE THREAD

**Issue by jtan7th** [hkgnp/logseq-todoist-plugin#48]
Hi - great app man, thanks for making this!

I've been trying to pull all tasks for last couple of days but it isnt' working.

Pulling today's tasks has been fine though.

After I type the command the cursor just continues blinking and nothing happens whereas today's tasks results in the relevant tasks appearing under "inbox" with the deadline and name of task appearing accordingly.

Anything I might be doing wrong or a potential bug?

**Comment by hkgnp** [comment]
Apologies I think there was a bug that was introduced somehow. Please update to the latest version and try again.
Thank you.

**Comment by jtan7th** [comment]
I just tried again - today's works, but still no good for all tasks post update.

**Comment by jtan7th** [comment]
Hey @hkgnp - just heads up think the new update may have broke the plugin. I tried updating to the newest version and it's still not working

**Comment by jtan7th** [comment]
It's a bit finicky - I just managed to get "Today's" tasks to come through, but not the overdue ones. 

I also just moved the overdue ones to "today" and tried pulling again but it didn't work.

**Comment by hkgnp** [comment]
Please try v5.0.3.

**Comment by jtan7th** [comment]
It works thanks man!
