### ISSUE TITLE
Can't Get a List of Projects

### ISSUE THREAD

**Issue by GregPetrov** [hkgnp/logseq-todoist-plugin#49]
Hello!
First of all thank you much for this plugin. Very useful and time saving!

Today I was not able to send a task.
Checked the plugin settings.
The plugin can't get access to the list of my Todoist projects and as a result can't send the task.

I tried recreate the app in Todoist and enter new test token.
LogSeq is restarted several times.
OS is restarted.

I also noticed that the plugin window where "Submit token" button is situated according to installation guide now not available after the plugin installation.

Any help is appreciated.
Thanks in advance.

**Comment by hkgnp** [comment]
The submit token button has been deprecated some time ago when the new settings api was released. Apologies as I have yet to update the `README`.

Can you take a screenshot of your plugin settings page but grey out your token?

**Comment by GregPetrov** [comment]
@hkgnp thanks for your response!

Screenshot is attached. 

<img width="741" alt="Screenshot 2022-11-29 at 10 26 50" src="https://user-images.githubusercontent.com/6481387/204467740-e9f280f8-4456-42b7-8f20-e39a43b30df1.png">
<img width="734" alt="Screenshot 2022-11-29 at 10 38 01" src="https://user-images.githubusercontent.com/6481387/204467751-dcadeef4-4ddf-4897-969c-8cf93e11107d.png">

**Comment by hkgnp** [comment]
Thank you.

Hmm, I just tested and everything seems to be working. I have not made any
changes to the code for several months now. Can I also verify your Logseq
version and plugin version that you are using?

**Comment by GregPetrov** [comment]
@hkgnp shame on me!

I also made logout / login in the Todoist and everything works excellent!
Sorry for taking your time.

**Comment by hkgnp** [comment]
No worries!
