### ISSUE TITLE
:bug: No Task Customization for Sending Tasks Under Linux

### ISSUE THREAD

**Issue by mruderman** [hkgnp/logseq-todoist-plugin#50]
Hello, thank you for developing :heart: 

Under Ubuntu 20.04 LogSeq v0.8.11

My JSON settings are:
`{
  "apiToken": "916e3b2d821b18d15366563a9538b1303aeeec79",
  "pullDefaultProject": "---",
  "pullDefaultAppend": true,
  "addParentBlock": true,
  "clearTasks": false,
  "sendDefaultProject": "---",
  "sendDefaultDeadline": false,
  "sendDefaultLabel": "---",
  "appendLogseqUri": "Link description",
  "appendTodoistUrl": "Append link",
  "appOrWebLink": "WebLink",
  "disabled": false
}`

When I attempt to send tasks, there is no pop-up window asking for the due date, project, priority.

I have tested this with the same settings on LogSeq v0.8.1.1 under Windows and it works correctly as expected there, just not working with Ubuntu.

Thanks again.

**Comment by array** [comment]
Same thing is happening with Todoist on Windows 11.

**Comment by mruderman** [comment]
Uninstalling and reinstalling the plugin worked for me...However, now the plugin is rejecting my API key, even though I can confirm I can pull information using the key with a curl command.

**Comment by mruderman** [comment]
OK, with release of plugin 4.4.3. reinstall, the API is recognized again and the pop-up menu is back. Thanks @hkgnp !!!!

**Comment by hkgnp** [comment]
Wow that's fast! Sounds great!
