### ISSUE TITLE
Problem with installing the plugin to a new instance of Logseq.

### ISSUE THREAD

**Issue by tmark00** [hkgnp/logseq-todoist-plugin#51]
If you install Logseq to a new computer you must install 4.4.3 version of plugin first. Otherwise you will not see the page with settings. Later you can update.

**Comment by elihubogan** [comment]
Confirming I have the same issue with installing from marketplace (5.2.0 version). Clicking the settings gear icon opens 'todoist-logsec-plugin.json' in my IDE. 

I don't know how to go about installing a previous version - maybe add that to installation instructions as a stopgap until the bug is fixed? Thanks!

**Comment by hkgnp** [comment]
Should be fixed in 5.2.1. Please try.

**Comment by elihubogan** [comment]
> Should be fixed in 5.2.1. Please try.

Confirmed, the settings page opens fine in 5.2.1 (logseq 0.8.16). Thanks!

**Comment by tmark00** [comment]
Unfortunately now adding logseq link and todoist link do not work now. Possibility to add todoist link to the task does not even shows in settings.

**Comment by hkgnp** [comment]
> The settings menu displays now. Unfortunately now adding logseq link and todoist link do not work now. Possibility to add todoist link to the task does not even shows in settings.

Could you take a screenshot of your settings page?

**Comment by tmark00** [comment]
Hi,
I sending you json

Kind regards,
Tomasz Markiewicz

{
  "apiToken": "xxxxxx",
  "": "",
  "sendDefaultProject": "--- ---",
  "sendDefaultLabel": "--- ---",
  "sendDefaultDeadline": false,
  "sendAppendUri": true,
  "retrieveDefaultProject": "De Woenselse Poort (2300499389)",
  "projectNameAsParentBlk": false,
  "retrieveAppendTodo": true,
  "retrieveAppendUrl": true,
  "retrieveClearTasks": false,
  "enableTodoistSync": true,
  "disabled": false,
  "pullDefaultProject": "",
  "pullDefaultAppend": true,
  "addParentBlock": "false",
  "clearTasks": true,
  "appendLogseqUri": "Link description",
  "appendTodoistUrl": "Append link",
  "appOrWebLink": "app"
}

niedz., 15 sty 2023 o 00:53 hkgnp ***@***.***> napisał(a):

**Comment by tmark00** [comment]
And screenshots:

[image: image.png]
[image: image.png]

niedz., 15 sty 2023 o 00:53 hkgnp ***@***.***> napisał(a):

**Comment by tmark00** [comment]
I have updated screenshoots in previous post .
