### ISSUE TITLE
Feature Request: Option to not insert todoist id to each pulled tasks

### ISSUE THREAD

**Issue by Soleone** [hkgnp/logseq-todoist-plugin#52]
In Logseq I don't care about the "implementation detail" that I'm using Todoist. I am just using Todoist as a way to quickly export browser tabs into Logseq.

It adds a lot of noise if I pull 10 tasks (web page urls) into Logseq and each one is displaying the todoist id. Imho it makes sense to disable displaying that by default, but if not at least an option to turn it off would be awesome.

Thanks for considering!

**Comment by hkgnp** [comment]
I believe you can turn this off in the plugin settings. Please try toggling the setting below:

<img width="454" alt="Screenshot 2023-01-13 at 7 06 43 AM" src="https://user-images.githubusercontent.com/47936793/212200317-a5f26437-dde1-4396-bad6-c02b93ac213a.png">

**Comment by elihubogan** [comment]
> I believe you can turn this off in the plugin settings. Please try toggling the setting below:
> 
> <img alt="Screenshot 2023-01-13 at 7 06 43 AM" width="454" src="https://user-images.githubusercontent.com/47936793/212200317-a5f26437-dde1-4396-bad6-c02b93ac213a.png">

I have toggled the setting (off by default). The todoistid shows in both cases.

**Comment by Soleone** [comment]
Yes, agreed. The URL is separate from the id.

I think the id might get added all the time now to support bidirectional sync back to Todoist (which I don't need).

**Comment by hkgnp** [comment]
Apologies I mis-read the comment. You can find the section in `config.edn` and add `todoistid` to `:block-hidden-properties`.

```
 ;; hide specific properties for blocks
 ;; E.g. :block-hidden-properties #{:created-at :updated-at}
 :block-hidden-properties #{:todoistid}
```

**Comment by Soleone** [comment]
Thanks that works, and even fixes the blocks that have already been imported before. An option in he UI settings would be nice, so people won't have to have knowledge about this feature of hiding certain properties, but I think this is a fair workaround to close this issue.

So to summarize:

1. Open Logseq general settings
2. Click the `Edit config.cdn` button next to Custom configuration
3. Add this line: ` :block-hidden-properties #{:todoistid}`

**Comment by hkgnp** [comment]
I think putting it in the plugin settings means I have to access to Logseq DOM which I try to avoid as much as possible. What I do need to do is to actually update the README, which I have been pushing back for a really long time!
