### ISSUE TITLE
Feature Request: Retrieve Tasks with Customized Filters

### ISSUE THREAD

**Issue by AnyonicFugue** [hkgnp/logseq-todoist-plugin#56]
Hi! Customized filters would allow me to retrieve tasks due today in a certain project, which is a great convenience. I guess many would find filters useful in various ways :)

By the way, Todoist supports filters in restful APIs. https://developer.todoist.com/rest/v2/#get-active-tasks

Thanks in advance!

**Comment by hkgnp** [comment]
Available in latest release. See https://github.com/hkgnp/logseq-todoist-plugin/issues/67#issuecomment-1704443838.
