### ISSUE TITLE
No subtask pulled

### ISSUE THREAD

**Issue by masonfocus** [hkgnp/logseq-todoist-plugin#59]
Firstly, thank you for this extension since it is the exact tool I need to incorporate logseq with todoist. 谢谢

But I encounter a few problems:

1. No subtask is pulled, however I change the settings, with/without project title, clear/keep original tasks.
2. The subtask problem even persist when I pull today's tasks, not only subtasks will not show as hierarchy, they won't show at all.
3. I cannot send task with priority or project with block properties.
4. Tasks pulled comes with a property "todoistid", which is not useful as the link is in the task title, and it is not tidy to view, how can i change that?
<img width="239" alt="image" src="https://user-images.githubusercontent.com/8166351/225485143-93a2ba9b-e00d-4548-991d-659a9ac6b413.png">
   

My settings are:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/8166351/225484812-9b1849f1-e3c0-4404-8e4e-b457ea6005b6.png">

I'm using Logseq 0.8.18 with the 5.1.2 version of extension.

**Comment by hkgnp** [comment]
(1) and (2) are fixed.

For (4), find the below line in your `config.edn` file and make changes as per below:
```
 ;; hide specific properties for blocks
 ;; E.g. :block-hidden-properties #{:created-at :updated-at}
:block-hidden-properties #{:todoistid}
```

For (3), let me review that.

**Comment by masonfocus** [comment]
Thank you, after upgrading, the problem 1,2,4 are solved, but 3 still exist.

**Comment by masonfocus** [comment]
It seemed that pulling today's tasks have a new bug now:

if sync is enabled, when pulling today's task, only tasks in the designated subject are pulled (just like syncing the project) regardless of the deadline of the mission.

**Comment by hkgnp** [comment]
Should be solved in latest release.
