### ISSUE TITLE
Feature Request: Auto-Updating

### ISSUE THREAD

**Issue by adamcaudill** [hkgnp/logseq-todoist-plugin#6]
Ideally, it would be nice to be able to automatically pull new tasks from Todoist without manual interaction. This is especially true if you use [email to bring in new tasks to Todoist](https://todoist.com/help/articles/forwarding-emails-to-todoist#forwarding-to-projects), and thus they can show up at any time.

At first glance, Logseq doesn't seem to have a good way to allow a plugin to perform actions at a regular intervals, so I'm guessing this will require a feature request to Logseq (that will be useful for a number of other plugins in the future).

**Comment by hkgnp** [comment]
Thanks @adamcaudill for the idea. Certainly something interesting to think about!
