### ISSUE TITLE
Send task with default options without pop-up window

### ISSUE THREAD

**Issue by sandrofsousa** [hkgnp/logseq-todoist-plugin#61]
Awesome plugin, kudos to the developers for putting it together!

I noted that the new update now opens a window when submitting a task, which is cool, but it creates friction for quickly capturing a task (more clicks). This happens despite a default project being set, is this expected behaviour, or is there something I could do to avoid it? Is there a way to set this functionality off? 

e.g.:
![image](https://github.com/hkgnp/logseq-todoist-plugin/assets/7435099/6c4225fd-59b6-4fc2-b823-88abd36b7071)

Expected behaviour:
As shown in the repo animation.

**Comment by DevTalking** [comment]
Agree, this will increase efficiency.

**Comment by yoghurtdewdew** [comment]
Agree+1. If there will be an option to use default setting without asking.

**Comment by hkgnp** [comment]
Should be solved in latest release.

**Comment by yoghurtdewdew** [comment]
Hi! Thanks for your great work! The popup really stopped to show, while there is a wried tag and no Logseq URL

<img width="875" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/c68dc791-fae2-4a36-b3c0-9e45af06d240">

**Comment by hkgnp** [comment]
Can you take a photo of your settings without your API token?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
