### ISSUE TITLE
appended property which I don't need

### ISSUE THREAD

**Issue by asiyoua** [hkgnp/logseq-todoist-plugin#65]
**I can't figure out this problem: when I pull tasks from retrived tasks, the blocks show the properties as the picture shows.
Did I get something wrong?**

![image](https://github.com/hkgnp/logseq-todoist-plugin/assets/48462903/a69769d7-f65a-46b5-b1b9-f9aaf73c30a5)
![image](https://github.com/hkgnp/logseq-todoist-plugin/assets/48462903/77e13309-25aa-47ca-929f-f3d4dc45e691)

**Comment by yoghurtdewdew** [comment]
Agree+1. Options for properties to keep clean.

**Comment by BodyJack** [comment]
I have the same problem :( Please fix it for coffea 👍

**Comment by hkgnp** [comment]
This is related to: https://github.com/logseq/logseq/issues/9279. Unfortunately, this is the new Logseq behaviour.

**Comment by yoghurtdewdew** [comment]
Will there be an option to not sync the property of attachment and comments? Actually, I do not use them.

**Comment by hkgnp** [comment]
You may hide them via your `config.edn`. Find out more here: https://discuss.logseq.com/t/control-which-block-properties-are-hidden-in-view-mode/884/6

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yoghurtdewdew** [comment]
Thanks for your great work and useful advice!
