### ISSUE TITLE
Could not send to Todoist with Logseq URI link.

### ISSUE THREAD

**Issue by yoghurtdewdew** [hkgnp/logseq-todoist-plugin#66]
I see an option to Append Logseq URI. I opened this option but see no Logseq URI link in Todoist after sending tasks. Is that normal?
And I see #37 and thought that would be awesome. While, now I could not send to Todoist with Logseq URI link.
<img width="485" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/bb42d9f4-da44-453f-98f2-3888cb1e1eee">
<img width="631" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/402cd824-c8e2-466c-8f19-477eaa8d3981">

**Comment by hkgnp** [comment]
Should be solved in latest release.

**Comment by yoghurtdewdew** [comment]
<img width="1111" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/b4bf2780-9ac6-47a1-94a4-0950e5ffc86c">

<img width="352" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/9735473b-5b59-4ff9-8857-345e17dfc723">

Thanks for your great work! But I still could not get the Logseq URL in tasks sended to Todoist.
And the tags showed as numbers.

**Comment by hkgnp** [comment]
Can you screenshot your entire settings page  please?

**Comment by hkgnp** [comment]
It looks like you are not at the latest version. Can you update the plugin please?

**Comment by ard0gg** [comment]
I am also seeing behavior this on v5.1.1

**Comment by yoghurtdewdew** [comment]
<img width="330" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/14ad426f-ea06-4d7f-aa4c-db9adf33f43e">
<img width="327" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/570a4c01-cc53-48f9-864c-38d2f380b459">


I tried it showed: up to date

**Comment by hkgnp** [comment]
Hmm it should be on v5.1.1, and not 5.2.7. Could you uninstall the plugin, quit Logseq, and install it again?

The settings in the latest version does not have `Todoist Sync` at the bottom.

**Comment by yoghurtdewdew** [comment]
Thanks v5.1.3 worked nice!
