### ISSUE TITLE
I can not retrieve today's tasks from Todoist.  version 5.2.6

### ISSUE THREAD

**Issue by TsutomuZ** [hkgnp/logseq-todoist-plugin#68]
I can not retrieve today's tasks from Todoist. 
version 5.2.6
Logseq 0.9.15
I can do "Send Task" only.
I reinstalled the plugin.
I changed the API.
However, I cannot retrieve today's tasks from Todoist.

**Comment by hkgnp** [comment]
Hi,

Sorry I just merged a few PRs from fellow contributors. Not sure if it broke something. Maybe you can revert the version?
________________________________
From: Tsutomu ***@***.***>
Sent: Thursday, August 24, 2023 10:32 AM
To: hkgnp/logseq-todoist-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hkgnp/logseq-todoist-plugin] I can not retrieve today's tasks from Todoist. version 5.2.6 (Issue #68)


I can not retrieve today's tasks from Todoist.
version 5.2.6
Logseq 0.9.15
I can do "Send Task" only.
I reinstalled the plugin.
I changed the API.
However, I cannot retrieve today's tasks from Todoist.

**Comment by TsutomuZ** [comment]
Thank you for your response.
I could retrieve today's tasks from Todoist.
I used version 5.2.4.
I hope this bug is fixed soon.

**Comment by andreoliwa** [comment]
It should be fixed when this is merged: https://github.com/hkgnp/logseq-todoist-plugin/pull/69

You can reopen this issue.

**Comment by TsutomuZ** [comment]
Thank you for your reply. I used plugin version 5.2.7 and was able to retrieve today's tasks. However, in version 5.2.7, tasks are being retrieved from all projects, even though I have set the Default project in the settings.

**Comment by andreoliwa** [comment]
> in version 5.2.7, tasks are being retrieved from all projects, even though I have set the Default project in the settings.

Can you open a separate issue for this?
Maybe it's also related to https://github.com/hkgnp/logseq-todoist-plugin/pull/62 but I can't check the code at the moment.
