### ISSUE TITLE
Are due dates the same as deadlines? Can't get the due date to set properly when sending tasks to Todoist.

### ISSUE THREAD

**Issue by robbernabe** [hkgnp/logseq-todoist-plugin#71]
Hi there! Thanks for this amazing plugin.  Works beautifully for me, but have a question and potential issue with due dates on tasks being sent to Todoist.

Are deadlines (as referred to in the settings) the same as due dates? I've tried setting both deadlines and schedules for tasks in Logseq, then sending those over to Todoist, but nothing seems to set the `due` field on my tasks.  I checked in the developer tools network section and confirmed that the payload sent to Todoist always seems to have `due` set to `null`, so it just seems like we're not sending it over.  

Running Logseq v0.9.17 and v5.0.2 of your plugin.  Any help would be appreciated.  Thanks!

**Comment by hkgnp** [comment]
Thanks for reporting! Will look into it.

**Comment by hkgnp** [comment]
This is resolved in the latest version.

**Comment by robbernabe** [comment]
Amazing! Works like a charm, much appreciated 🍻
