### ISSUE TITLE
Cannot Send Task to Todoist

### ISSUE THREAD

**Issue by ard0gg** [hkgnp/logseq-todoist-plugin#72]
I can retrieve tasks just fine. However, when I try to send a task, the side bar pops up, but clicking "Send Task" doesn't appear to do anything.

**Comment by ard0gg** [comment]
Here are my settings:
![image](https://github.com/hkgnp/logseq-todoist-plugin/assets/415023/c77c76cf-8a51-489e-a44e-447385ef04f3)

**Comment by hkgnp** [comment]
Please try the latest version.

**Comment by ard0gg** [comment]
Sending Tasks fixed in v5.1.1
