### ISSUE TITLE
Todist: Send Task sets Deadline as Today when no deadline is chosen

### ISSUE THREAD

**Issue by ard0gg** [hkgnp/logseq-todoist-plugin#73]
See title. 
In my settings I  have left "unchecked" sendDefaultDeadline
![image](https://github.com/hkgnp/logseq-todoist-plugin/assets/415023/14a1e098-9a78-4ce5-aa88-405f04567a1f)

However, sent tasks still have deadline of Today.

**Comment by hkgnp** [comment]
Did you add a default project?

**Comment by ard0gg** [comment]
I have tried both with a default project and without by using the project selection in the pop up menu. Both result in a deadline of Today being added. Even though deadline may be blank in the pop up, it still defaults to Today when sent to Todoist.

**Comment by ard0gg** [comment]
Without a default project, when sending via the pop up menu, if I type in "No Date" in the Set a Deadline field, then the task in todoist will properly show with no deadline.

**Comment by hkgnp** [comment]
May I know what version are you on?

**Comment by ard0gg** [comment]
![image](https://github.com/hkgnp/logseq-todoist-plugin/assets/415023/c383fbcb-9e22-4530-8929-0de79d909cad)
v5.1.1

**Comment by hkgnp** [comment]
Do you expect that if you don't use the pop up and a default project is specified, no due date is specified?

**Comment by ard0gg** [comment]
That is my expectation when setDefaultDeadline is unchecked.

**Comment by hkgnp** [comment]
Ok let me see what I can do.

**Comment by hkgnp** [comment]
Please try the latest version.

**Comment by ard0gg** [comment]
It works! Thank you!
