### ISSUE TITLE
Deadlines for months >=10 fail to send

### ISSUE THREAD

**Issue by michellaevens** [hkgnp/logseq-todoist-plugin#74]
Hi - Logseq tasks with deadlines after September will not transfer to Todoist or will have a wrong due date in Todoist.

I tried to fix or at least locate the bug but I don't have the tools to test changes. I could only see the POST msg with API through dev tools.

**Comment by hkgnp** [comment]
Hi, I am not able to reproduce it. Do you have a specific example please?

**Comment by michellaevens** [comment]
Will send screenshots today. I forgot to mention it's the deadline property
in the task block, not in the sidebar

**Comment by michellaevens** [comment]
pls, find the screenshot. when turning the variable deadline into a string seems to be part of the issue.
![b1](https://github.com/hkgnp/logseq-todoist-plugin/assets/6659858/a19b93cd-2417-4448-a265-a632dee5a3dd)

**Comment by hkgnp** [comment]
Thanks for the screenshots. Fixed in latest version!
