### ISSUE TITLE
Custom appended format of logseq url 

### ISSUE THREAD

**Issue by yoghurtdewdew** [hkgnp/logseq-todoist-plugin#75]
<img width="886" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/38e44e14-9b98-4b96-85bb-d44c3da053a9">

<img width="733" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/1b8ed13a-e383-4a3d-bbc5-03bc6d890f3c">

Will there be a possibility to show logseq url not inline?

Because I will send things with multiple formats. Hope it would be separately appended or customed as `BLOCK CONTENT [l↗️](logseq://graph/Documents?block-id=BLOCKID)`

**Comment by hkgnp** [comment]
Hi! Sorry I am not sure what you mean? Do you have some examples to share?

**Comment by yoghurtdewdew** [comment]
Suggest that in Logseq: `[[logseq]] 嘿嘿 [有个链接](https://111)` and its BLOCKID=`651920d9-8ac5-4f3b-98d8-a33547b82d86` —— And it will be better to be turned into `[[logseq]] 嘿嘿 [有个链接](https://111) [t↗️](todoist://project?id={id})`

I hope that in todoist: `[[logseq]] 嘿嘿 [有个链接](https://111) [l↗️](logseq://graph/Documents?block-id=651920d9-8ac5-4f3b-98d8-a33547b82d86)`, instead of `[[[logseq]] 嘿嘿 [有个链接](https://0.0.0.111/)](logseq://graph/Documents?block-id=651560f1-1e3d-4bf4-8260-878b13cc8576)`

Will this be more clear for understanding?

**Comment by hkgnp** [comment]
Sorry, it's still not very clear. Could you show two screenshots side-by-side of what it looks like in Todoist and in Logseq?

**Comment by hkgnp** [comment]
Ok I think I get what you mean. It's a good idea. I have implemented it in the latest version.

**Comment by yoghurtdewdew** [comment]
Hi! I think I should put screenshot to make it clear.

Now it showed: unclickable task-url when the task include the url:

<img width="620" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/a638772d-72cb-4f07-b627-bf20003e3976">

<img width="577" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/2a4473a3-3a47-41ad-9c0a-0e1ec04b61ef">

**What I wanted:** 

First, the task-url was seperately showed and was directly clickable with the clickable Todoist-url (the `⤴️` `↗️` could be changed into custom characters by users).

Second, Todoist-url could be changed into deeplink like `todoist://task?id={id}`, so the click of Todoist-deep url will show task in Todoist app, instead of open the webpage (open task in webpage will be much slower than open in app).

<img width="473" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/06f26c53-09aa-4e65-9440-0e01dd82d16e">

<img width="599" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/2c3265ef-54d4-4daa-985f-f601c61b4acb">

(I have updated to version 5.1.9)
