### ISSUE TITLE
Seemed to have dupilicate options

### ISSUE THREAD

**Issue by yoghurtdewdew** [hkgnp/logseq-todoist-plugin#76]
<img width="472" alt="image" src="https://github.com/hkgnp/logseq-todoist-plugin/assets/63794438/7611ede7-b772-4d3d-aa80-eb666fd5f205">

Would you mind tell the diffrences between the two options? They looks like the same.

**Comment by hkgnp** [comment]
It's a bug. Should be fixed in the latest version.
