### ISSUE TITLE
[feature request] Pull in all tasks assigned to today, regardless of project

### ISSUE THREAD

**Issue by aadilayub** [hkgnp/logseq-todoist-plugin#8]
It'd be great if there were an option to pull in tasks that are due for today, instead of pulling in tasks for a specific project. It would look sort of like this:

![image](https://user-images.githubusercontent.com/31581044/142302109-450438fa-f78f-41a7-a2fa-69b341bce21d.png)

**Comment by hkgnp** [comment]
Thanks for the feature request. Will look into the Todoist API again to see if it's possible.

**Comment by hkgnp** [comment]
@aadilayub can I confirm with you that your workflow actually includes indicating the prefix in Todoist before pulling it over?

**Comment by aadilayub** [comment]
Nope, it wouldn't! I only use prefixes in Logseq. It would be nice if the default prefix (TODO or LATER) would be assigned to the tasks when they are pulled in, so that they are visually distinct from note bullets.

**Comment by hkgnp** [comment]
Feature implemented in the latest release. Please run an update, or download the latest version from the marketplace.
Cheers!

**Comment by aadilayub** [comment]
Amazing! Thank you <3
