### ISSUE TITLE
Hi there, it is not really a issue is a Feature suggestion to try to solve a problem

### ISSUE THREAD

**Issue by PyPlot** [hkgnp/logseq-todoist-plugin#9]
So, this plugin would be perfect! for my Workflow Process but unfortunately it doesn't give the option to don't delete Todoist's tasks after them being pulled. So this becomes useless for people that need to keep the tasks on Todoist.

Is there a way to add that feature, I can give some help if it is needed!

Best regards,
AL

**Comment by hkgnp** [comment]
Hi!

Feature request now available on v2.4! Do an update on the marketplace and you should be able to now toggle the option of clearing tasks or not!

**Comment by PyPlot** [comment]
> Hi!
> 
> Feature request now available on v2.4! Do an update on the marketplace and you should be able to now toggle the option of clearing tasks or not!

Hi there, you I noticed in the meanwhile, great work!!
